spring.application.name=HospitalManagement
spring.datasource.url=jdbc:postgresql://localhost:5432/hospitalManagement
spring.datasource.username=postgres
spring.datasource.password=2226@Sai
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update






#spring.datasource.url=jdbc:postgresql://dpg-d7tie88sfn5c73ap7cbg-a:5432/hospitalmanagement_ujnq
#
#spring.datasource.username=sai
#spring.datasource.password=kdyJ8Ns0GiRS08Zz6OTjXQDn9T4HkD6M
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update


#postgresql://sai:kdyJ8Ns0GiRS08Zz6OTjXQDn9T4HkD6M@dpg-d7tie88sfn5c73ap7cbg-a/hospitalmanagement_ujnq

